package day8

import (
	"strings"
	"testing"
)

func TestSolvePart1(t *testing.T) {
	input := `..........
..........
..........
....a.....
..........
.....a....
..........
..........
..........
..........`
	lines := strings.Split(input, "\n")
	want := 2
	got := solvePart1(lines)
	if got != want {
		t.Errorf("solvePart1 want %d got %d", want, got)
	}

	input = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`

	lines = strings.Split(input, "\n")
	want = 14
	got = solvePart1(lines)
	if got != want {
		t.Errorf("solvePart1 want %d got %d", want, got)
	}
}

func TestSolvePart2(t *testing.T) {
	input := `T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........`

	lines := strings.Split(input, "\n")
	want := 9
	got := solvePart2(lines)
	if got != want {
		t.Errorf("solvePart1 want %d got %d", want, got)
	}

	input = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`

	lines = strings.Split(input, "\n")
	want = 34
	got = solvePart2(lines)

	if got != want {
		t.Errorf("solvePart1 want %d got %d", want, got)
	}
}
